# -*- coding: utf-8 -*-
"""homeTask_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PKN7cKddzesOHnOLCyW1JH9DfecxiEZo

Задача 1. Найдите, какая область центрального федерального округа имела наибольшую численность студентов вечерней формы обучения в 2015 году.
"""

import pandas as pd
import seaborn as sns
import google.colab as files

df = pd.read_csv('/content/data20152019.csv', sep =';', encoding="cp1251") 
df_2019 = df.iloc[2:20, :4]
df_2019

df_2019.max()

"""Задача 2 Постройте диаграмму с данными о численности студентов дневной формы обучения южного федерального округа за 2017 год."""

task_2 = df.iloc[33:41, :7]
task_2

plot = sns.barplot(task_2,x = 'Субъект РФ', y = 'Численность студентов, очная форма, человек, 2017' )
plot.set_xticklabels(labels= task_2['Субъект РФ'],rotation = 90)

"""Задача 3 Постройте диаграмму количества студентов заочной формы обучения за 2019 год по всем регионам, в которых общее количество студентов не превышает 10000 за данный год."""

task_3 = df
task_3

task_3[task_3['Численность студентов заочная форма, человек, 2019'].between(0,10000)]

plot = sns.barplot(task_3,x = 'Субъект РФ', y = 'Численность студентов заочная форма, человек, 2019' )
plot.set_xticklabels(labels= task_3['Субъект РФ'],rotation = 90)

df.to_csv('hometask_10.csv')
files.files.download('hometask_10.csv')